query($login: String!) {
  user(login: $login) {
    followers {totalCount}
    contributionsCollection {
      totalCommitContributions
      totalPullRequestContributions
      totalIssueContributions
      restrictedContributionsCount
      commitContributionsByRepository(maxRepositories: 100) {
        repository { nameWithOwner }
        contributions(
          first: 1
          orderBy: {field: OCCURRED_AT, direction: DESC}
        ) {
          nodes { occurredAt }
        }
      }
    }
    repositories (
      first: 100
      ownerAffiliations: OWNER
      isFork: false
      orderBy: {field: PUSHED_AT, direction: DESC }
    ) {
      totalCount
      nodes {
        nameWithOwner
        stargazerCount
        languages(first: 10, orderBy: { field: SIZE, direction: DESC }) {
          edges { size node { name } }
        }
      }
    }
    repositoriesContributedTo(
      first: 100
      contributionTypes: [COMMIT, ISSUE, PULL_REQUEST, REPOSITORY]
      includeUserRepositories: false
    ) {
      totalCount
      nodes {
        nameWithOwner
        languages(first: 10, orderBy: { field: SIZE, direction: DESC }) {
          edges { size node { name } }
        }
      }
    }
  }
}
